name: Build Draw Matches

on:
  workflow_dispatch:

jobs:
  build-draw:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

    steps:
      - name: Run build_draw_matches RPC
        run: |
          curl -X POST "${SUPABASE_URL}/rest/v1/rpc/build_draw_matches" \
            -H "apikey: ${SUPABASE_KEY}" \
            -H "Authorization: Bearer ${SUPABASE_KEY}" \
            -H "Content-Type: application/json" \
            -d '{"p_tournament_id":"2025-429"}'

