name: api-smoke-matchup

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "main.py"
      - "services/**"
      - "utils/**"
      - ".github/workflows/ci_api_smoke_matchup.yml"

jobs:
  smoke:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      SR_API_KEY: ${{ secrets.SR_API_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else pip install flask requests; fi
          sudo apt-get update && sudo apt-get install -y jq

      - name: Start app on 127.0.0.1:8080
        run: |
          nohup python - <<'PY' &
          from main import app
          app.run(host="127.0.0.1", port=8080)
          PY
          # espera simple a que el servidor levante
          sleep 5

      - name: Call /matchup (smoke)
        run: |
          PAYLOAD='{"tournament":{"name":"Cincinnati","month":8},"years_back":4}'
          RESP=$(curl -sS -X POST http://127.0.0.1:8080/matchup -H "Content-Type: application/json" -d "$PAYLOAD")
          echo "$RESP" | jq .
          # asserts mínimos
          echo "$RESP" | jq -e '.ok == true' >/dev/null
          echo "$RESP" | jq -e 'has("prob_player")' >/dev/null
