name: api-smoke-bracket

on:
  workflow_dispatch:

jobs:
  bracket:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      SR_API_KEY:   ${{ secrets.SR_API_KEY }}
      PORT: "8080"

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          set -e
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install flask
          fi

      - name: Sanity env
        run: |
          set -e
          [ -n "$SUPABASE_URL" ] || { echo "::error::SUPABASE_URL missing"; exit 1; }
          [ -n "$SUPABASE_KEY" ] || { echo "::error::SUPABASE_KEY missing"; exit 1; }
          if [ -z "$SR_API_KEY" ]; then echo "::warning::SR_API_KEY missing (seguirá con histórico)"; fi
          test -f apps_scripts/start_api.py || { echo "::error::apps_scripts/start_api.py no existe"; exit 1; }
          test -f apps_scripts/simulate_bracket.py || { echo "::error::apps_scripts/simulate_bracket.py no existe"; exit 1; }

      - name: Start API (Flask) on ${{ env.PORT }}
        run: |
          set -e
          nohup python -u apps_scripts/start_api.py > app.log 2>&1 &
          for i in $(seq 1 40); do
            if curl -sf http://127.0.0.1:${PORT}/health  >/dev/null 2>&1; then break; fi
            if curl -sf http://127.0.0.1:${PORT}/healthz >/dev/null 2>&1; then break; fi
            sleep 1
          done
          if ! (curl -sf http://127.0.0.1:${PORT}/health >/dev/null 2>&1 || curl -sf http://127.0.0.1:${PORT}/healthz >/dev/null 2>&1); then
            echo "::error::API no responde"; tail -n 200 app.log || true; exit 1
          fi

      - name: Simular bracket (8 jugadores)
        run: |
          set -e
          python apps_scripts/simulate_bracket.py

      - name: app.log (tail if fail)
        if: failure()
        run: |
          echo "----- app.log (tail) -----"
          tail -n 200 app.log || true
