name: db-fs-hist-winrates

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - sql/migrations/2025_08_25_speed_compat_view.sql
      - sql/migrations/2025_08_25_fs_hist_winrates.sql
      - .github/workflows/ci_db_fs_hist_winrates.yml

jobs:
  apply:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - uses: actions/checkout@v4

      - name: Install psql
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Apply compat patch (speed_bucket)
        run: |
          [ -n "$DATABASE_URL" ] || { echo "::error::DATABASE_URL missing"; exit 1; }
          test -f sql/migrations/2025_08_25_speed_compat_view.sql
          psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f sql/migrations/2025_08_25_speed_compat_view.sql
          psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -c "\d+ public.court_speed_rankig_norm_compat"

      - name: Apply FS historic RPCs
        run: |
          test -f sql/migrations/2025_08_25_fs_hist_winrates.sql
          psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f sql/migrations/2025_08_25_fs_hist_winrates.sql

      - name: Verify RPCs exist
        run: |
          psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -c \
            "select proname, proargtypes from pg_proc where proname in ('fs_month_winrate','fs_surface_winrate','fs_speed_winrate');"

      - name: Quick check compat view
        run: |
          psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -c \
            "select tournament_name, surface, speed_rank, speed_bucket from public.court_speed_rankig_norm_compat limit 3;"
