name: db-tourney-alias-finalize

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - sql/migrations/2025_08_27_tourney_alias_finalize.sql
      - .github/workflows/ci_db_tourney_alias_finalize.yml

jobs:
  apply:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Apply finalize migration
        run: |
          [ -n "$DATABASE_URL" ] || { echo "::error::DATABASE_URL missing"; exit 1; }
          psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f sql/migrations/2025_08_27_tourney_alias_finalize.sql

      - name: Sanity checks
        run: |
          psql "$DATABASE_URL" -c "\df+ public.norm_tourney"
          psql "$DATABASE_URL" -c "\d+ public.tourney_speed_resolved"
          psql "$DATABASE_URL" -c "SELECT count(*) AS suggestions FROM public.tourney_key_suggestions;"
          psql "$DATABASE_URL" -c "SELECT count(*) AS orphans FROM public.tourney_key_map_orphans;"
