name: db-perf-indexes
on: workflow_dispatch
jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Apply indexes
        env: 
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          set -e
          [ -n "$DATABASE_URL" ] || { echo "::error::DATABASE_URL missing"; exit 1; }
          psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f sql/migrations/2025_08_28_perf_indexes.sql
