name: DB – Create & Backfill defense_points (prev year)

on:
  workflow_dispatch:
    inputs:
      season_year:
        description: "Año a usar como 'previo' (ej. 2024)"
        required: true
        default: "2024"

jobs:
  build-defense-points:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SEASON_YEAR: ${{ inputs.season_year }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sanity – psql connectivity
        run: psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -c "select now();"

      - name: Setup Python (to write SQL files)
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Generate SQL files (view + upsert + export)
        run: |
          python - << 'PY'
          import os, pathlib, textwrap
          year = int(os.environ.get("SEASON_YEAR","2024"))
          outdir = pathlib.Path("/tmp")

          # 1) Helper + tabla destino
          (outdir/"defense_setup.sql").write_text(textwrap.dedent(f"""
            CREATE OR REPLACE FUNCTION public.norm_tourney(txt text)
            RETURNS text LANGUAGE sql IMMUTABLE AS $$
              SELECT regexp_replace(lower(coalesce(txt,'')), '\\s+', ' ', 'g')
            $$;

            CREATE TABLE IF NOT EXISTS public.player_defense_prev_year (
              tourney_key text NOT NULL,
              player_id   int  NOT NULL,
              points      int  NOT NULL,
              title_code  text,
              PRIMARY KEY (tourney_key, player_id)
            );
          """).strip()+"\n", encoding="utf-8")

          # 2) VIEW usando norm_tourney(tournament_name) como clave
          (outdir/"defense_view.sql").write_text(textwrap.dedent(f"""
            DROP VIEW IF EXISTS public.v_defense_points_prev_year CASCADE;

            CREATE VIEW public.v_defense_points_prev_year AS
            WITH base AS (
              SELECT
                public.norm_tourney(m.tournament_name) AS tourney_key,
                m.match_date,
                m.player_id,
                m.opponent_id,
                m.winner_id
              FROM public.fs_matches_long m
              WHERE EXTRACT(YEAR FROM m.match_date) = {year}
            ),
            tourney_cat_raw AS (
              SELECT
                b.tourney_key,
                COALESCE(tsr.category, csr.category) AS raw_category
              FROM (SELECT DISTINCT tourney_key FROM base) b
              LEFT JOIN public.tourney_speed_resolved tsr
                ON tsr.tourney_key = b.tourney_key
              LEFT JOIN public.court_speed_rankig_norm csr
                ON public.norm_tourney(csr.tournament_name) = b.tourney_key
            ),
            tourney_cat AS (
              SELECT
                tourney_key,
                CASE
                  WHEN raw_category ILIKE '%grand%'   THEN 'Grand Slam'
                  WHEN raw_category ILIKE '%master%'  THEN 'Masters'
                  WHEN raw_category ILIKE '%1000%'    THEN 'Masters'
                  WHEN raw_category ILIKE '%500%'     THEN 'ATP500'
                  WHEN raw_category ILIKE '%250%'     THEN 'ATP250'
                  ELSE 'ATP250'
                END AS category
              FROM tourney_cat_raw
            ),
            finals AS (
              SELECT
                tourney_key,
                MAX(match_date) AS final_date
              FROM base
              GROUP BY 1
            ),
            final_match AS (
              SELECT DISTINCT ON (f.tourney_key)
                f.tourney_key,
                b.match_date,
                b.winner_id,
                CASE
                  WHEN b.player_id = b.winner_id THEN b.opponent_id
                  ELSE b.player_id
                END AS runner_id
              FROM finals f
              JOIN base b
                ON b.tourney_key = f.tourney_key
               AND b.match_date = f.final_date
              ORDER BY f.tourney_key, b.match_date DESC
            ),
            points AS (
              SELECT 'Grand Slam'::text AS category, 2000 AS champ, 1200 AS runner UNION ALL
              SELECT 'Masters'::text,                 1000,  600  UNION ALL
              SELECT 'ATP500'::text,                   500,  300  UNION ALL
              SELECT 'ATP250'::text,                   250,  150
            ),
            champs AS (
              SELECT
                fm.tourney_key,
                fm.winner_id AS player_id,
                p.champ      AS points,
                'champ'      AS title_code
              FROM final_match fm
              JOIN tourney_cat tc USING (tourney_key)
              JOIN points p ON p.category = tc.category
            ),
            runners AS (
              SELECT
                fm.tourney_key,
                fm.runner_id AS player_id,
                p.runner     AS points,
                'runner'     AS title_code
              FROM final_match fm
              JOIN tourney_cat tc USING (tourney_key)
              JOIN points p ON p.category = tc.category
            )
            SELECT * FROM champs
            UNION ALL
            SELECT * FROM runners;
          """).strip()+"\n", encoding="utf-8")

          # 3) Upsert desde la vista
          (outdir/"defense_upsert.sql").write_text(textwrap.dedent("""
            INSERT INTO public.player_defense_prev_year (tourney_key, player_id, points, title_code)
            SELECT tourney_key, player_id, points, title_code
            FROM public.v_defense_points_prev_year
            ON CONFLICT (tourney_key, player_id) DO UPDATE
            SET points = EXCLUDED.points,
                title_code = EXCLUDED.title_code;
          """).strip()+"\n", encoding="utf-8")

          # 4) Export CSV
          (outdir/"defense_export.sql").write_text(textwrap.dedent("""
            COPY (
              SELECT *
              FROM public.v_defense_points_prev_year
              ORDER BY tourney_key, points DESC, player_id
            ) TO STDOUT WITH CSV HEADER;
          """).strip()+"\n", encoding="utf-8")

          print("Wrote:", "/tmp/defense_setup.sql")
          print("Wrote:", "/tmp/defense_view.sql")
          print("Wrote:", "/tmp/defense_upsert.sql")
          print("Wrote:", "/tmp/defense_export.sql")
          PY

      - name: Apply setup (function + table)
        run: psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f /tmp/defense_setup.sql

      - name: Create/replace view v_defense_points_prev_year
        run: psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f /tmp/defense_view.sql

      - name: Upsert player_defense_prev_year from view
        run: psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f /tmp/defense_upsert.sql

      - name: Export view to CSV
        run: |
          mkdir -p /tmp/defense_artifacts
          psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f /tmp/defense_export.sql > /tmp/defense_artifacts/defense_points_prev_year.csv
          echo "CSV rows:"; wc -l /tmp/defense_artifacts/defense_points_prev_year.csv || true

      - name: Verify table sample
        run: |
          echo ">>> Sample from player_defense_prev_year:"
          psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -c "SELECT * FROM public.player_defense_prev_year ORDER BY tourney_key, points DESC, player_id LIMIT 20;"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: defense_points_prev_year
          path: /tmp/defense_artifacts/defense_points_prev_year.csv
          retention-days: 7
