name: Load ATP Tournament

on:
  workflow_dispatch:
    inputs:
      tourney_id:
        description: "Tournament ID (e.g., 2025-747)"
        required: true
      pdf_url:
        description: "Draw PDF URL"
        required: true

jobs:
  load-draw:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests pandas pdfplumber

      - name: Step 1 - Upsert tournament
        run: |
          python apps_script/upsert_tournament.py "${{ github.event.inputs.tourney_id }}"

      - name: Step 2 - Download PDF and generate CSV
        run: |
          python apps_script/get_atp_draws.py "${{ github.event.inputs.pdf_url }}" "data/draw_${{ github.event.inputs.tourney_id }}.csv"

      - name: Step 3 - Load CSV to staging
        run: |
          python apps_script/load_draw_to_staging.py "data/draw_${{ github.event.inputs.tourney_id }}.csv"

      - name: Step 4 - Migrate from staging
        run: |
          python apps_script/load_from_staging.py "${{ github.event.inputs.tourney_id }}"

      - name: Step 5 - Build draw matches
        run: |
          curl -X POST "${SUPABASE_URL}/rest/v1/rpc/build_draw_matches" \
            -H "apikey: ${SUPABASE_KEY}" \
            -H "Authorization: Bearer ${SUPABASE_KEY}" \
            -H "Content-Type: application/json" \
            -d '{"p_tournament_id": "${{ github.event.inputs.tourney_id }}"}'
