name: Full Tournament Loader

description: Carga completa de cuadro desde PDF oficial (protennislive)

on:
  workflow_dispatch:
    inputs:
      tourney_id:
        description: "ID del torneo (ej: 2025-329)"
        required: true
      pdf_url:
        description: "URL del PDF oficial (ej: https://www.protennislive.com/posting/2025/329/mds.pdf)"
        required: true

jobs:
  load-draw:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests pdfplumber

      - name: Descargar PDF y generar CSV
        run: |
          python apps_script/get_atp_draws.py "${{ github.event.inputs.pdf_url }}" "data/draw_${{ github.event.inputs.tourney_id }}.csv"

      - name: Cargar CSV a staging
        run: |
          python apps_script/load_draw_to_staging.py "data/draw_${{ github.event.inputs.tourney_id }}.csv" --tourney_id "${{ github.event.inputs.tourney_id }}"

      - name: Cargar staging a draw_entries
        run: |
          python apps_script/load_from_staging.py "${{ github.event.inputs.tourney_id }}"

      - name: Generar draw_matches
        run: |
          curl -X POST "${SUPABASE_URL}/rest/v1/rpc/build_draw_matches" \
            -H "apikey: ${SUPABASE_KEY}" \
            -H "Authorization: Bearer ${SUPABASE_KEY}" \
            -H "Content-Type: application/json" \
            -d '{"p_tourney_id": "${{ github.event.inputs.tourney_id }}"}'
