name: Load Draw CSV to Staging

on:
  workflow_dispatch:

jobs:
  load-draw:
    runs-on: ubuntu-latest
    env:
      SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install psycopg2-binary pandas

      - name: Load CSV to staging
        run: |
          python apps_script/load_draw_to_staging.py data/draw_329.csv
