name: Migrate Staging to Draw Entries

on:
  workflow_dispatch:
    inputs:
      tourney_id:
        description: 'Tourney ID (ej: 2025-329)'
        required: true
        type: string

jobs:
  migrate-draw:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install requests

      - name: Run staging migration
        run: |
          python apps_script/load_from_staging.py ${{ inputs.tourney_id }}
